name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  auto_push:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.name "andikaakbr"
        git config --global user.email "andika.uciha99@gmail.com"

    - name: Commit and Push Changes
      run: |
        git commit -am "Auto commit"
        git push
